### ISSUE TITLE
Mission 9 Objective List Formatting

### ISSUE THREAD

**Issue by andrew-hossack** [UNL-UAV/unl-uav.github.io#18]
List of rules is formatted incorrectly under Mission 9 Objective on the Home page.

Table incorrectly looks like:
1.
2.
3. a. b.
4.

Table should look like:
1.
2.
3. 
\t a. 
\t b.
4.
( a and b need to be set by spaces or tabs)

**Comment by Root3287** [comment]
Do you want something like the following?

1. Foo
2. Bar
3. Hello
  a. World
  b. Another List

```markdown
1. Foo
2. Bar
3. Hello
  a. World
  b. Another List
```

Edit: Alphabetized list is also not supported by native markdown. Using ```*``` list instead

**Comment by Root3287** [comment]
Fixed in my up coming pr
