### ISSUE TITLE
Change image size on https://unl-uav.github.io/teams/ Hardware

### ISSUE THREAD

**Issue by andrew-hossack** [UNL-UAV/unl-uav.github.io#8]
Resize to 400?

**Comment by Root3287** [comment]
Could you explain more?

**Comment by andrew-hossack** [comment]
Please resize the image under hardware to 400 width

**Comment by Root3287** [comment]
Looking at this more this is more of a picture issue. Adding a different image...

**Comment by andrew-hossack** [comment]
Closed. Fixed in merge on #10.
